spring:
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/youtube_share?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DBUser:}
    password: ${DBPwd:}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect

jwt:
  secret: 4c4d328d2fe052962698ec4ed63afbb7c9171629b9502498d9faabe19b29e0a3